# Generated by Django 5.0.6 on 2024-09-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(max_length=30)),
                ('requestee', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'followRequests',
            },
        ),
        migrations.CreateModel(
            name='UserBioAndLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=30, unique=True)),
                ('bio', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'userBiondLinks',
            },
        ),
    ]
