# Generated by Django 5.0.6 on 2024-09-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userbioandlink_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbioandlink',
            name='id',
        ),
        migrations.AlterField(
            model_name='userbioandlink',
            name='username',
            field=models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('requester', 'requestee')},
        ),
    ]
